### ISSUE TITLE
go-plus plugin cannot find virtualgo installed packages

### ISSUE THREAD

**Issue by kinghadi** [GetStream/vg#38]
I'm using `Atom` and `go-plus` plugin. After I installed `grpc` package, the `go-plus` showed the following error:

    main.go:8:2: cannot find package "google.golang.org/grpc" in any of:
    /usr/local/opt/go/libexec/src/google.golang.org/grpc (from $GOROOT)
    /[mypath]/src/google.golang.org/grpc (from $GOPATH)

but I can run it in the terminal without any error:

    go run main.go

**Comment by kinghadi** [comment]
I close the issue because it has to be handled by `go-plus` plugin.

**Comment by JelteF** [comment]
Thanks for the report, obviously I haven't tried `vg` with all editors and plugins. Usually you can quite easily make it work set `GOPATH` in some way though, because that's basically all that `vg` does. As an example look at: https://github.com/GetStream/vg#using-a-virtualgo-workspace-with-an-ide-eg-goland
